name: pospischill.net
favicon: null
layout_spectrum: 0
typography_spectrum: 0.61303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#030303'
    - '#b4937f'
    - '#153844'
    - '#772536'
  brandStrength: 0.875
  lightness: 0.3125
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
