name: pospischill.net
favicon: null
layout_spectrum: 0.19158
typography_spectrum: 0.41935
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#121212'
    - '#877d73'
    - '#d5d3d4'
    - '#77a8a4'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.5
purpose: []
