name: pospischill.net
favicon: null
layout_spectrum: 0.37541
typography_spectrum: 0.84681
title: pospischill.net
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e5dd'
    - '#423e36'
    - '#1b1a16'
    - '#d09d7d'
    - '#655b1f'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
