title: pospischill.net
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5
  brandStrength: 0.8125
  rhythmicContrast: 0.5
  brandColors:
    - '#e9e5dd'
    - '#423e36'
    - '#1b1a16'
    - '#d09d7d'
    - '#655b1f'
  lightness: 0.625
cta:
  version: null
  bucket: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: pospischill.net
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.9041353
layout_spectrum: 0.3095238
